### ISSUE TITLE
*UDPConn.Serve() leads to > 100% CPU load

### ISSUE THREAD

**Issue by notnot** [scgolang/osc#5]
I have noticed that an application that i am developing which uses package osc has > 100% CPU load even when no OSC messages come in, when i build my executable with go1.9 and go1.10 on OS X 10.10 and 10.12. When i build with go1.7 and 1.8 the CPU load is just a few %, as expected. My application uses GLFW and OpenGL, it is fairly small and simple still, but it depends on some external hardware. I could try and make a more minimal application that doesn't have these dependencies and send you the source.

**Comment by briansorahan** [comment]
Closing this as it sounds like it isn't an issue anymore
