### ISSUE TITLE
Error in timetag to time.Time conversion

### ISSUE THREAD

**Issue by tleb** [scgolang/osc#6]
I know this library is probably not used anymore, I just want to make sure no one gets bitten by it. The timetag to `time.Time` conversion is invalid. See hypebeast/go-osc#56 where I reported the same bug in another (/ the other?) Go OSC library. [The code is here](https://github.com/scgolang/osc/blob/ba4a707618ec302feb8a03997d1cc6778c1c7f5f/timetag.go#L44-L72).

The spec describes the lower 32 bits of the timetag as fractions of a second. That means each increment is `1e9/(2^32) s = ~0.233 ns`. Currently, each increment equals one nanosecond.

If this lib is still used, I will happily provide a patch.

**Comment by avlapp** [comment]
Why aren't people using this package anymore? I'm interested, if it's easy for you to provide a patch, you're welcome.

**Comment by avlapp** [comment]
Why aren't people using this package anymore? I'm interested, if it's easy for you to provide a patch, you're welcome. @tleb

**Comment by briansorahan** [comment]
Merged #13 (after creating my own branch from it to add a test case)
